#include "wifiscan.h"
#include "screen.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

// the scan.txt file is generated by iwlist with certain filters applied. Each network
// is organized as a Cell and written in 4 lines: 
/*
          Cell 04 - Address: 00:06:B1:2D:C5:9D
          Frequency:2.432 GHz (Channel 5)
          Quality=34/70  Signal level=-76 dBm
          ESSID:"sonicwall"
*/                                                                      
void read_data(void){
	FILE *fp;
	char line[200]; 	// a line of data
	WIFI_INFO wf, wf_list[100];		// a list for all networks
	int i=0, c;	// line counter, changes between 0 to 3
	
	if((fp = fopen(SFILE, "r"))==NULL){
		printf("Cannot open file %s\n", SFILE); return;
	}
	while(fgets(line, 200, fp)!=NULL){	// read file line by line
#ifdef DEBUG
//		printf("Line read: %s", line);
#endif
		remove_spaces(line);	// remove leading spaces of the line
		if(strncmp(line, "Cell", 4)==0){	// first line of a Cell
			c = 0;		// set line counter to 0
			//printf("New cell\n");
			get_MAC(line, wf.MAC);	// the first line contains MAC of AP
		}
		else{
			c++; 		// line counter increments
			if(c==1)	// 2nd line, contains frequency/channel No.
				wf.channel = get_channel(line);
			if(c==2)	// 3rd line, contains signal level (RSSI)
				wf.slevel = get_slevel(line);
			if(c==3){	// the last line contains ESSID
				get_essid(line, wf.essid);
				wf_list[i++] = wf;	// copy the current wifi to list
			}
		}
	}
	fclose(fp);
	printf("%d networks found\n", i);
	displayNetworks(wf_list, i);
}

void displayNetworks(WIFI_INFO wlist[], int c){
	int i;
	clearScreen();
#ifdef DEBUG
	printf("%3s%10s%10s%10s%30s\n", "###", "Channel", "Freq.", "dBm", "ESSID");
	for(i=0; i<80; i++) putchar('-'); 
	puts("");
#else
	gotoXY(1,1); setFGcolor(YELLOW); printf("%d Networks", c); resetColors();
	setFGcolor(WHITE);	// display x-axis (channel numbers)
	for(i=0; i<13; i++){
		gotoXY(36, 13+i*5); printf("%d", i+1);
	}
#endif
	for(i=0; i<c; i++){
		wlist[i].frequency = 2.412 + 0.005*(wlist[i].channel-1);
#ifdef DEBUG
		printf("%3d%10d%10.3f%10d%30s\n", i+1, wlist[i].channel, 
				wlist[i].frequency, wlist[i].slevel, wlist[i].essid);
#else	// the screen is sized at least 35 rows and 80 columns 
		// top row shows some summary info, the 2nd row to 34th row shows dBm values
		// between -30 to -90 as 2dBm/row. The bottom row shows channel number
		// each column represents 1MHz, color is varying between RED (31) to WHITE (37)
		disp(wlist[i], i);
#endif
	}
}

// this function displays one network on the screen, using screen functions.
void disp(WIFI_INFO w, int c){
	int row, col;
	setFGcolor(RED + c%7);	
	row = (-30-w.slevel)/2 + 1;
	col = (w.channel-1)*5+13;
	drawRect(row, col-11, 35-row, 22);
	gotoXY(row, col-strlen(w.essid)/2);
	printf("%-s", w.essid);
	resetColors();
}

// the output of "iwlist" makes a number of spaces at front of each line,
// in order to read the data, those spaces need to be removed. This function
// finds the first non-space character of s[] and uses strcpy function to 
// move the partial string to the beginning of s[]
void remove_spaces(char s[]){
	int i, len=strlen(s);
	for(i=0; i<len; i++){
		// loop stops when the first non-space char found
		if(s[i]!=' ' && s[i]!='\t' && s[i]!='\n') break;
	}
	strcpy(s, &s[i]);	// copy the partial string to original string
}

// this function find MAC address from the first line of a Cell
// this line is always formatted by iwlist as
// "Cell xx - Address: xx:xx:xx:xx:xx:xx"
// so, simply locate the 19th element of line, and use sscanf to 
// scan 6 hexadecimal values into macaddr
void get_MAC(char line[], char ma[]){
	sscanf(&line[19], "%hhx:%hhx:%hhx:%hhx:%hhx:%hhx",
		&ma[0], &ma[1], &ma[2], &ma[3], &ma[4], &ma[5]);
#ifdef DEBUG	// output MAC in another form
	//printf("%02x-%02x-%02x-%02x-%02x-%02x\n",
	//	ma[0], ma[1], ma[2], ma[3], ma[4], ma[5]);
#endif
}

// this function finds the channel number of a Cell. The line given as argument is formatted as
// 			"Frequency:2.432 GHz (Channel 5)"
// we can find ')' the the white space in front of the number. And copy the substring to a 
// temp string and convert it to integer. The frequency can be calculated by channel number.
int get_channel(char s[]){
	int i, j, len = strlen(s);
	char temp[10] = {'\0'};		// a temporal string, initialized by null char
	
	for(i=0; i<len; i++) 	// find ')'
		if(s[i]==0x29) break;
	
	for(j=i; j>=0; j--)		// find the white space in front of it.
		if(s[j]==' ') break;
	
	strncpy(temp, &s[j+1], i-j-1);
	return atoi(temp);
}

// this function find signal level of a Cell. The input string is formatted as 
//  "Quality=34/70  Signal level=-76 dBm"
// we can find 2nd '=' sign and copy the rest 3 chars to a temporal string, and
// convert it as an integer
int get_slevel(char s[]){
	int i, c, len = strlen(s);
	char temp[10];
	
	for(i=0, c=0; i<len; i++){
		if(s[i] == '='){
			if(++c == 2) break;	// found 2nd '=' sign
		}
	}
	strncpy(temp, &s[i+1], 3); 
	return atoi(temp);
}

// this function find ESSID of a cell, the input argument is a line formatted in this way:
// 	\"ESSID:"sonicwall"\"
// Find the first '"' symbol, and copy the rest of line to a new string, then in the 
// target string find '"' symbol and replace it by null character
void get_essid(char s[], char id[]){
	int i, len = strlen(s);
	for(i=0; i<len; i++)
		if(s[i]=='"') break;	// we found the first '"' sign
	
	strcpy(id, &s[i+1]);		// copy the rest of line to id
	for(i=0; i<strlen(id); i++){
		if(id[i]=='"') break;	// found the ending '"'
	}
	id[i] = '\0';		// replace it by null char
}